-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS main;

CREATE TABLE IF NOT EXISTS main.test
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    min_level_correct smallint NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main.test
    IS 'Тест';

COMMENT ON COLUMN main.test.id
    IS 'Идентификатор';

COMMENT ON COLUMN main.test.name
    IS 'Название';

COMMENT ON COLUMN main.test.min_level_correct
    IS 'Минимальное кол-во правильных ответов для прохождения теста';

CREATE TABLE IF NOT EXISTS main.question
(
    id bigint NOT NULL,
    name character varying(1000) NOT NULL,
    test_id integer NOT NULL,
    image bytea,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main.question
    IS 'Вопрос';

COMMENT ON COLUMN main.question.id
    IS 'Идентификатор';

COMMENT ON COLUMN main.question.name
    IS 'Название';

COMMENT ON COLUMN main.question.test_id
    IS 'Идентификатор теста';

COMMENT ON COLUMN main.question.image
    IS 'Изображение';

CREATE TABLE IF NOT EXISTS main.answer
(
    id bigint NOT NULL,
    name character varying(1000) NOT NULL,
    is_correct boolean NOT NULL DEFAULT false,
    question_id bigint NOT NULL,
    image bytea,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main.answer
    IS 'Ответ на вопрос';

COMMENT ON COLUMN main.answer.id
    IS 'Идентификатор';

COMMENT ON COLUMN main.answer.name
    IS 'Название';

COMMENT ON COLUMN main.answer.is_correct
    IS 'Признак правильного ответа';

COMMENT ON COLUMN main.answer.question_id
    IS 'Иденитфикатор вопроса';

COMMENT ON COLUMN main.answer.image
    IS 'Изображение';

CREATE TABLE IF NOT EXISTS main."user"
(
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    pwd character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main."user"
    IS 'Пользователь';

COMMENT ON COLUMN main."user".id
    IS 'Идентификатор';

COMMENT ON COLUMN main."user".name
    IS 'Имя';

COMMENT ON COLUMN main."user".pwd
    IS 'Пароль';

CREATE TABLE IF NOT EXISTS main.user_test
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    test_id integer NOT NULL,
    started timestamp without time zone NOT NULL,
    finished timestamp without time zone,
    number_correct_questions integer NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main.user_test
    IS 'Текущий или завершенный тест пользователя';

COMMENT ON COLUMN main.user_test.id
    IS 'Идентификатор';

COMMENT ON COLUMN main.user_test.user_id
    IS 'Идентификатор пользователя';

COMMENT ON COLUMN main.user_test.test_id
    IS 'Идентификатор теста';

COMMENT ON COLUMN main.user_test.started
    IS 'Начало теста';

COMMENT ON COLUMN main.user_test.finished
    IS 'Окончание теста';

COMMENT ON COLUMN main.user_test.number_correct_questions
    IS 'Кол-во правильно отвеченных вопросов';

CREATE TABLE IF NOT EXISTS main.user_test_detail
(
    id bigint NOT NULL,
    user_test_id bigint NOT NULL,
    question_id bigint NOT NULL,
    answer_id bigint NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE main.user_test_detail
    IS 'Подробные данные по каждому тесту пользователя';

COMMENT ON COLUMN main.user_test_detail.id
    IS 'Идентификатор';

COMMENT ON COLUMN main.user_test_detail.user_test_id
    IS 'Идентификатор теста';

COMMENT ON COLUMN main.user_test_detail.question_id
    IS 'Идентификатор вопроса';

COMMENT ON COLUMN main.user_test_detail.answer_id
    IS 'Идентификатор ответа';

ALTER TABLE IF EXISTS main.question
    ADD FOREIGN KEY (test_id)
    REFERENCES main.test (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS main.answer
    ADD FOREIGN KEY (question_id)
    REFERENCES main.question (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS main.user_test
    ADD FOREIGN KEY (user_id)
    REFERENCES main."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS main.user_test
    ADD FOREIGN KEY (test_id)
    REFERENCES main.test (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS main.user_test_detail
    ADD FOREIGN KEY (user_test_id)
    REFERENCES main.user_test (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

COMMIT;